### ISSUE TITLE
JSONObject["hits"] not found.

### ISSUE THREAD

**Issue by tosunkaya** [yassinesabri/spring-mysql-elastic#3]
Something is wrong with Elasticsearch. When i GET http://localhost:8080/search/query/tes
getting null and JSONObject["hits"] not found on output. i have user that first name and last name test test
Can you help me? 
http://localhost:8080/user/find-all works.

I fixed this by adding authentication header. But now have other problems.

**Comment by yassinesabri** [comment]
@tosunkaya can you provide me with your pom.xml dependencies details and the version of the elasticsearch engine you're connected to please?

**Comment by tosunkaya** [comment]
hi. i fixed by editing on thymeleaf html files. can u help about query on thymeleaf? At the moment it shows as string (JSON) not as object (on normal controller (i added), not REST controller)

has some problems about this.
https://docs.spring.io/spring-data/elasticsearch/docs/current-SNAPSHOT/reference/html/#elasticsearch.query-methods.finders

**Comment by yassinesabri** [comment]
@tosunkaya you can use [json dependancy](https://mvnrepository.com/artifact/org.json/json) to convert the stringify element to a JSON object

**Comment by tosunkaya** [comment]
I used gson to converting but getting internet server error. Maybe i should use by "keywords for Elasticsearch" like findByContaining added this but got different error. :(

Here is my Normal Controller file:

if i use `model.addAttribute("query",searchService.searchFromQuery(query.trim().toLowerCase()) );` it shows as JSON string on results.

```
	@GetMapping("/searchresults/{query}")
    public String  searchResultsFoods(@PathVariable String query, Model model) throws IOException {
		
        //model.addAttribute("foods", this.userService.findAll()); // i will add a if, if query is blank show all if not show query
             Gson g = new Gson();
             //ResultQuery sa= searchService.searchFromQuery(query.trim().toLowerCase());
             String saa= searchService.searchFromQuery(query.trim().toLowerCase()).toString();
             g.toJson(saa, User.class);
             //g.toJson(searchService.searchFromQuery(query.trim().toLowerCase()), sa));

//User u = g.fromJson(searchService.searchFromQuery(query.trim().toLowerCase())), User.class);
//String a = searchService.searchFromQuery(query.trim().toLowerCase());
        //model.addAttribute("query",searchService.searchFromQuery(query.trim().toLowerCase()) );
         model.addAttribute("query",saa );
		return "searchresults";
}
```

HTML thymeleaf searchresults.html (only related part) SHOWS AS STRING:
```
<tbody>
	<tr th:each="food : ${query}">
        <td th:text="${food.elements}">
        <!--<td th:text="${food.id}"></td>
	<td th:text="${food.firstName}"></td>
	<td th:text="${food.lastName}"></td> I NEED LIKE THIS-->
	</tr>
	</tbody>
```

findALL (index): https://i.stack.imgur.com/66vao.png
query search result: /searchresults/asd: https://i.stack.imgur.com/FhRyU.png

**Comment by yassinesabri** [comment]
Closing the issue due to inactivity.
